### ISSUE TITLE
Show Notifications despite the App was closed

### ISSUE THREAD

**Issue by pavangayakwad** [marbetschar/time-limit#31]
So, Am I missing something here?

I set the time, close the app and it never alerts me! If the app expects it to be live on the screen then very reason of time-alert app is defeated.

**Comment by marbetschar** [comment]
There is no background service, so if you close the app the timer is gone too. However, the timer app does not need to be in foreground in order to alert you - it only expects to be running.

Please note, there is a [pending bug which avoids beeing alerted while "do not disturb" is active](https://github.com/marbetschar/time-limit/issues/26). This issue is related due to how notifications are handled within elementary and is fixed as soon as the [new notifications are ready](https://github.com/elementary/notifications/).

That said, this issue seems to be a usage error so I'm closing it for now. Feel free to reopen if you see fit.

**Comment by marbetschar** [comment]
will re-evaluate on Odin, maybe this can be achieved with the new notification server once it is available.
