### ISSUE TITLE
[Feature request] Pin to top

### ISSUE THREAD

**Issue by prkmk** [marbetschar/time-limit#75]
### Problem

Sometimes, it would be beneficial to see the timer at all times. However, changing the active window might hide the timer.

### Proposal

Implement a button (toggle?) to keep the timer on the top. Pin button or similar. Here's an example:
![Frame 14](https://user-images.githubusercontent.com/46991062/186403103-8a879d6a-6830-430d-adf7-9b4a3489b35a.png)

// EDIT: This can already be achieved with Picture-in-picture mode

**Comment by marbetschar** [comment]
Hi @prkmk,

Thanks for your issue report. There is already a builtin feature of elementary to achieve exactly what you are looking for :) Simply right click on the top bar of Time Limit and enable "Always on Top". Here's a screenshot of how that looks like:

![Screenshot from 2022-08-24 16 51 49@2x](https://user-images.githubusercontent.com/392542/186450850-14b64a13-f510-45ad-853b-36087fb5b4ae.png)

Since this can be achieved with builtin mechanisms of elementary, I'm closing the issue for now.
